# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group_members_max',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='course',
            name='group_members_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='content_html',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='content_md',
            field=models.TextField(null=True),
        ),
    ]
