# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursearticle',
            name='belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_set', to='backend.Course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='coursearticle',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='学生上交截止时间'),
        ),
    ]
