# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '创建中'), (4, '已完成'), (7, '已锁定')], default=1, verbose_name='团队状态'),
        ),
    ]
