# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20171003_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('content_md', models.TextField(null=True)),
                ('content_html', models.TextField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('create_date',)},
        ),
        migrations.RemoveField(
            model_name='course',
            name='content_html',
        ),
        migrations.RemoveField(
            model_name='course',
            name='content_md',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.Article'),
            preserve_default=False,
        ),
    ]
