# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 05:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_code_set', to=settings.AUTH_USER_MODEL, verbose_name='受邀人'),
        ),
    ]
