# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-15 03:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180406_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursearticle',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_set', to=settings.AUTH_USER_MODEL, verbose_name='文章作者'),
        ),
        migrations.AlterField(
            model_name='grouparticle',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '创建中'), (3, '已提交'), (4, '已审完'), (5, '被驳回')], default=1, verbose_name='文章状态'),
        ),
        migrations.AlterField(
            model_name='grouparticle',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
    ]
