# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171123_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='choice',
            field=models.IntegerField(choices=[(1, '邀请加入团队'), (2, '邀请管理课程'), (3, '申请加入团队'), (4, '申请退出团队')], default=1),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_set', to='backend.Course'),
        ),
    ]
