# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20171003_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.CourseGroup'),
            preserve_default=False,
        ),
    ]
