# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20171008_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Article'),
        ),
    ]
