# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20171003_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Comment'),
        ),
    ]
