@startuml
title 学生团队组建流程
actor "小红" as U0
actor "小明" as U1
actor "小强" as UC
control "Web 后台" as B
database "数据库" as DB

== 申请创建团队 ==

UC -> B: 填写信息，申请创建小队
B -> DB: 小队信息存入
B -> UC: 小队创建成功

== 团队创建完成，开始邀请队友 ==

UC -> B: 邀请小明、小红入队
B -> UC: 知道了
B --> U0: 小强邀请你加入他的小队
B --> U1: 小强邀请你加入他的小队

== 等待回应(同意的情况) ==

U1 -> B: 同意加入小强的小队
B -> DB: 更新小队成员信息
B -> UC: 发送消息告知

== 等待回应(不同意的情况) ==
U0 -> B: 不同意加入小强的小队
B -> UC: 告知

@enduml
